### ISSUE TITLE
Unusual behavior of ide

### ISSUE THREAD

**Issue by iamjaspreetsingh** [Zilliqa/savant-ide#19] opened 2018-10-10 17:47 UTC
When i try checking my contract, the blank screen appears all of the sudden.
Please refer to the code from: https://gist.github.com/iamjaspreetsingh/e8c51eca3524f4a1efc8a2273ea5aec1

I doubt that it was working perfectly alright with old ide https://ide.zilliqa.com/

**Comment by iantanwx** [comment] 2018-10-10 23:48
@iamjaspreetsingh thanks for reporting this. It is related to #11. I’ll fix this as soon as I can.

**Comment by iantanwx** [comment] 2018-10-14 03:38
@iamjaspreetsingh I'm closing this as it's a duplicate of #11. Please follow that instead, if you're interested. Thanks!

**Closed by iantanwx** 2018-10-14 03:38 UTC
Labels: backend, bug, duplicate
